//! RMarkdown export functionality for Re-prod.
//!
//! This module provides two export modes:
//! - Timeline-based: Exports actual execution history from the timeline
//! - Document-based: Exports the current state of an R document
//!
//! # Example
//!
//! ```no_run
//! use reprod_core::export::{RMarkdownGenerator, RMarkdownOptions, ExportMode};
//! use reprod_core::export::ReproductionBundle;
//!
//! let options = RMarkdownOptions {
//!     mode: ExportMode::Timeline,
//!     include_timestamps: true,
//!     show_actor: true,
//!     embed_plots: true,
//!     include_outputs: true,
//!     include_errors: false,
//!     include_summary: true,
//! };
//!
//! let generator = RMarkdownGenerator::new(options);
//! let bundle = ReproductionBundle::from_events(vec![]);
//! let rmd_content = generator.from_timeline(&bundle);
//! ```

use super::bundle::ReproductionBundle;
use super::metadata::BundleMetadata;
use crate::protocol::{ExecutionActor, ExecutionEvent};
use serde::{Deserialize, Serialize};

/// Export mode for RMarkdown generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum ExportMode {
    /// Export from timeline (actual execution history)
    #[default]
    Timeline,
    /// Export from current document (edited file)
    Document,
}

/// Options for RMarkdown export.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RMarkdownOptions {
    pub mode: ExportMode,
    pub include_timestamps: bool,
    pub show_actor: bool,
    pub embed_plots: bool,
    pub include_outputs: bool,
    pub include_errors: bool,
    pub include_summary: bool,
}

impl Default for RMarkdownOptions {
    fn default() -> Self {
        Self {
            mode: ExportMode::Timeline,
            include_timestamps: true,
            show_actor: true,
            embed_plots: true,
            include_outputs: true,
            include_errors: false,
            include_summary: true,
        }
    }
}

/// RMarkdown generator for Re-prod exports.
pub struct RMarkdownGenerator {
    options: RMarkdownOptions,
}

impl RMarkdownGenerator {
    /// Create a new RMarkdown generator with the given options.
    pub const fn new(options: RMarkdownOptions) -> Self {
        Self { options }
    }

    /// Generate RMarkdown from timeline events (Mode A: Timeline-based).
    pub fn from_timeline(&self, bundle: &ReproductionBundle) -> String {
        let mut rmd = self.generate_yaml_header_timeline(bundle);
        rmd.push_str(&self.generate_session_info(bundle));
        rmd.push_str(&self.generate_timeline_events(bundle));
        if self.options.include_summary {
            rmd.push_str(&self.generate_summary(bundle));
        }
        rmd.push_str(&self.generate_footer());
        rmd
    }

    /// Generate RMarkdown from current document (Mode B: Document-based).
    pub fn from_document(
        &self,
        document_path: &str,
        document_content: &str,
        metadata: &BundleMetadata,
    ) -> String {
        let mut rmd = self.generate_yaml_header_document(document_path);
        rmd.push_str(&self.generate_document_overview(document_path));
        rmd.push_str(&self.extract_code_chunks(document_content));
        rmd.push_str(&self.generate_footer_document(metadata));
        rmd
    }

    // ===== Timeline Mode Helpers =====

    fn generate_yaml_header_timeline(&self, bundle: &ReproductionBundle) -> String {
        format!(
            r#"---
title: "Re-prod Analysis Report (Timeline Export)"
author: "Generated by Re-prod"
date: "{}"
output:
  html_document:
    toc: true
    toc_depth: 2
    code_folding: show
    theme: united
---

"#,
            bundle.metadata.created_at
        )
    }

    fn generate_session_info(&self, bundle: &ReproductionBundle) -> String {
        let duration_sec = bundle.metadata.session.duration_ms as f64 / 1000.0;
        format!(
            r#"# Session Information

- **Bundle ID**: {}
- **Created**: {}
- **Total Events**: {}
- **Duration**: {:.1} seconds

"#,
            bundle.metadata.bundle_id,
            bundle.metadata.created_at,
            bundle.metadata.session.total_events,
            duration_sec
        )
    }

    fn generate_timeline_events(&self, bundle: &ReproductionBundle) -> String {
        let mut content = String::from("# Timeline Export\n\n");
        content.push_str(
            "This document represents the **actual execution history** \
             captured by Re-prod. All code chunks were executed in the \
             order shown below.\n\n---\n\n",
        );

        for (i, event) in bundle.events.iter().enumerate() {
            content.push_str(&self.format_event(i + 1, event));
        }

        content
    }

    fn format_event(&self, index: usize, event: &ExecutionEvent) -> String {
        let mut section = String::new();

        // Actor heading
        if self.options.show_actor {
            let actor = match event.context.actor {
                ExecutionActor::User => "User",
                ExecutionActor::Ai => "AI Assistant",
            };
            section.push_str(&format!("## Event {} - {}\n\n", index, actor));
        } else {
            section.push_str(&format!("## Event {}\n\n", index));
        }

        // Metadata
        if self.options.include_timestamps {
            section.push_str(&format!(
                "**Executed**: {}  \n",
                format_timestamp(event.context.triggered_at_ms)
            ));
        }
        section.push_str(&format!("**Source**: {:?}  \n", event.context.source));
        if let Some(doc) = &event.context.document_path {
            section.push_str(&format!("**Document**: {}  \n", doc));
        }
        section.push('\n');

        // Code chunks
        for (block_idx, block) in event.blocks.iter().enumerate() {
            let chunk_id = format!("event-{}-block-{}", index, block_idx);
            section.push_str(&format!("```{{r {}}}\n", chunk_id));
            section.push_str(&block.code);
            if !block.code.ends_with('\n') {
                section.push('\n');
            }
            section.push_str("```\n\n");

            // Output
            if self.options.include_outputs && !event.result.output.is_empty() {
                section.push_str("**Output**:\n```\n");
                section.push_str(&event.result.output);
                if !event.result.output.ends_with('\n') {
                    section.push('\n');
                }
                section.push_str("```\n\n");
            }

            // Error
            if self.options.include_errors {
                if let Some(error) = &event.result.error {
                    section.push_str("**Error**:\n```\n");
                    section.push_str(error);
                    if !error.ends_with('\n') {
                        section.push('\n');
                    }
                    section.push_str("```\n\n");
                }
            }
        }

        // Plots
        if self.options.embed_plots && !event.result.plots.is_empty() {
            for plot in &event.result.plots {
                section.push_str(&format!("![Plot]({})\n\n", plot.filename));
            }
        }

        section.push_str("---\n\n");
        section
    }

    fn generate_summary(&self, bundle: &ReproductionBundle) -> String {
        let stats = &bundle.metadata.statistics;
        let total = stats.total_executions as f64;

        let user_pct = if total > 0.0 {
            (stats.user_actions as f64 / total) * 100.0
        } else {
            0.0
        };

        let ai_pct = if total > 0.0 {
            (stats.ai_actions as f64 / total) * 100.0
        } else {
            0.0
        };

        let duration_sec = bundle.metadata.session.duration_ms as f64 / 1000.0;

        format!(
            r#"# Session Summary

## Statistics

- **Total Executions**: {}
- **User Actions**: {} ({:.1}%)
- **AI Actions**: {} ({:.1}%)
- **Total Plots**: {}
- **Errors**: {}
- **Duration**: {:.2} seconds

## Environment

- **R Path**: {}
- **Platform**: {}
- **Working Directory**: {}
- **Re-prod Version**: {}

"#,
            stats.total_executions,
            stats.user_actions,
            user_pct,
            stats.ai_actions,
            ai_pct,
            stats.total_plots,
            stats.total_errors,
            duration_sec,
            bundle.metadata.environment.r_path,
            bundle.metadata.environment.platform,
            bundle.metadata.environment.working_dir,
            bundle.metadata.re_prod_version,
        )
    }

    fn generate_footer(&self) -> String {
        "\n---\n\n*Generated by Re-prod - Reproducible R Analysis Environment*\n".to_string()
    }

    // ===== Document Mode Helpers =====

    fn generate_yaml_header_document(&self, document_path: &str) -> String {
        let title = std::path::Path::new(document_path)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("R Analysis");

        format!(
            r#"---
title: "{}"
author: "Generated by Re-prod"
date: "{}"
output:
  html_document:
    toc: true
    code_folding: show
---

"#,
            title,
            chrono::Utc::now().format("%Y-%m-%d")
        )
    }

    fn generate_document_overview(&self, document_path: &str) -> String {
        format!(
            r#"# Overview

This document contains the R code from `{}`.

"#,
            document_path
        )
    }

    fn extract_code_chunks(&self, document_content: &str) -> String {
        let mut content = String::from("# Code\n\n");

        // Split by R section markers (# ---- or # ==== comments)
        let lines: Vec<&str> = document_content.lines().collect();
        let mut current_section = String::new();
        let mut section_number = 0;

        for line in lines {
            // Check for section headers (# Section ---- or # Section ====)
            if line.starts_with('#') && (line.contains("----") || line.contains("====")) {
                // Flush previous section if any
                if !current_section.trim().is_empty() {
                    section_number += 1;
                    content.push_str(&format!("```{{r chunk-{}}}\n", section_number));
                    content.push_str(&current_section);
                    if !current_section.ends_with('\n') {
                        content.push('\n');
                    }
                    content.push_str("```\n\n");
                    current_section.clear();
                }

                // Add section header as markdown
                let section_title = line
                    .trim_start_matches('#')
                    .replace("----", "")
                    .replace("====", "")
                    .trim()
                    .to_string();
                if !section_title.is_empty() {
                    content.push_str(&format!("## {}\n\n", section_title));
                }
            } else {
                current_section.push_str(line);
                current_section.push('\n');
            }
        }

        // Flush final section
        if !current_section.trim().is_empty() {
            section_number += 1;
            content.push_str(&format!("```{{r chunk-{}}}\n", section_number));
            content.push_str(&current_section);
            if !current_section.ends_with('\n') {
                content.push('\n');
            }
            content.push_str("```\n\n");
        }

        content
    }

    fn generate_footer_document(&self, metadata: &BundleMetadata) -> String {
        format!(
            r#"---

*Generated by Re-prod*
*Exported: {}*
*Re-prod Version: {}*
"#,
            metadata.created_at, metadata.re_prod_version
        )
    }
}

/// Format timestamp in milliseconds to human-readable format.
fn format_timestamp(ms: u64) -> String {
    let duration = chrono::Duration::milliseconds(ms as i64);
    let datetime = chrono::DateTime::<chrono::Utc>::from_timestamp(
        duration.num_seconds(),
        (duration.num_milliseconds() % 1000 * 1_000_000) as u32,
    )
    .unwrap_or_else(chrono::Utc::now);

    datetime.format("%Y-%m-%d %H:%M:%S UTC").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::{
        CodeBlockKind, CodeBlockMetadata, EnvironmentSnapshot, ExecutionContext, ExecutionResult,
        ExecutionSource, PlotInfo,
    };

    fn create_test_event(event_id: &str, actor: ExecutionActor, has_plot: bool) -> ExecutionEvent {
        ExecutionEvent {
            event_id: event_id.to_string(),
            context: ExecutionContext {
                source: ExecutionSource::Cell,
                document_path: Some("test.R".to_string()),
                cell_index: Some(1),
                triggered_at_ms: 1699200000000,
                actor,
            },
            blocks: vec![CodeBlockMetadata {
                id: "block-1".to_string(),
                index: 0,
                kind: CodeBlockKind::Section,
                label: Some("Test".to_string()),
                start_line: 1,
                end_line: 3,
                code: "x <- 1:10\nprint(x)".to_string(),
            }],
            result: ExecutionResult {
                success: true,
                output: "[1] 1 2 3 4 5".to_string(),
                error: None,
                plots: if has_plot {
                    vec![PlotInfo {
                        filename: "plots/plot_001.png".to_string(),
                        base64_data: "iVBORw0KG...".to_string(),
                        index: 0,
                    }]
                } else {
                    vec![]
                },
                execution_time_ms: 42,
            },
            environment: EnvironmentSnapshot {
                r_path: "Rscript".to_string(),
                working_dir: "/tmp/test".to_string(),
                temp_dir: "/tmp/reprod".to_string(),
            },
            created_at_ms: 1699200001000,
        }
    }

    #[test]
    fn test_timeline_export_basic() {
        let options = RMarkdownOptions::default();
        let generator = RMarkdownGenerator::new(options);

        let events = vec![
            create_test_event("evt-1", ExecutionActor::User, false),
            create_test_event("evt-2", ExecutionActor::Ai, false),
        ];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        // Check YAML header
        assert!(rmd.contains("---"));
        assert!(rmd.contains("title:"));
        assert!(rmd.contains("Re-prod Analysis Report"));

        // Check code chunks
        assert!(rmd.contains("```{r"));
        assert!(rmd.contains("x <- 1:10"));
        assert!(rmd.contains("print(x)"));

        // Check session summary
        assert!(rmd.contains("# Session Summary"));
        assert!(rmd.contains("Total Executions"));
    }

    #[test]
    fn test_timeline_export_with_actors() {
        let options = RMarkdownOptions {
            show_actor: true,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let events = vec![
            create_test_event("evt-1", ExecutionActor::User, false),
            create_test_event("evt-2", ExecutionActor::Ai, false),
        ];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        assert!(rmd.contains("Event 1 - User"));
        assert!(rmd.contains("Event 2 - AI Assistant"));
    }

    #[test]
    fn test_timeline_export_without_actors() {
        let options = RMarkdownOptions {
            show_actor: false,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let events = vec![create_test_event("evt-1", ExecutionActor::User, false)];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        assert!(rmd.contains("## Event 1\n"));
        // Check that actor labels are not in event headings
        assert!(!rmd.contains("## Event 1 - User"));
        assert!(!rmd.contains("## Event 1 - AI Assistant"));
    }

    #[test]
    fn test_timeline_export_with_plots() {
        let options = RMarkdownOptions {
            embed_plots: true,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let events = vec![create_test_event("evt-1", ExecutionActor::User, true)];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        assert!(rmd.contains("![Plot](plots/plot_001.png)"));
    }

    #[test]
    fn test_timeline_export_without_plots() {
        let options = RMarkdownOptions {
            embed_plots: false,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let events = vec![create_test_event("evt-1", ExecutionActor::User, true)];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        assert!(!rmd.contains("![Plot]"));
    }

    #[test]
    fn test_timeline_export_with_outputs() {
        let options = RMarkdownOptions {
            include_outputs: true,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let events = vec![create_test_event("evt-1", ExecutionActor::User, false)];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        assert!(rmd.contains("**Output**:"));
        assert!(rmd.contains("[1] 1 2 3 4 5"));
    }

    #[test]
    fn test_timeline_export_without_outputs() {
        let options = RMarkdownOptions {
            include_outputs: false,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let events = vec![create_test_event("evt-1", ExecutionActor::User, false)];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        assert!(!rmd.contains("**Output**:"));
        assert!(!rmd.contains("[1] 1 2 3 4 5"));
    }

    #[test]
    fn test_timeline_export_with_errors() {
        let options = RMarkdownOptions {
            include_errors: true,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let mut event = create_test_event("evt-1", ExecutionActor::User, false);
        event.result.error = Some("Error: object not found".to_string());

        let bundle = ReproductionBundle::from_events(vec![event]);
        let rmd = generator.from_timeline(&bundle);

        assert!(rmd.contains("**Error**:"));
        assert!(rmd.contains("Error: object not found"));
    }

    #[test]
    fn test_timeline_export_without_summary() {
        let options = RMarkdownOptions {
            include_summary: false,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let events = vec![create_test_event("evt-1", ExecutionActor::User, false)];
        let bundle = ReproductionBundle::from_events(events);
        let rmd = generator.from_timeline(&bundle);

        assert!(!rmd.contains("# Session Summary"));
    }

    #[test]
    fn test_document_export_basic() {
        let options = RMarkdownOptions {
            mode: ExportMode::Document,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let doc_content = "library(ggplot2)\nggplot(mtcars, aes(x = wt, y = mpg)) + geom_point()";
        let metadata = BundleMetadata::new("test-bundle".to_string());
        let rmd = generator.from_document("analysis.R", doc_content, &metadata);

        assert!(rmd.contains("---"));
        assert!(rmd.contains("title:"));
        assert!(rmd.contains("analysis"));
        assert!(rmd.contains("library(ggplot2)"));
        assert!(rmd.contains("ggplot(mtcars"));
    }

    #[test]
    fn test_document_export_with_sections() {
        let options = RMarkdownOptions {
            mode: ExportMode::Document,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let doc_content = r#"# Setup ----
library(ggplot2)

# Analysis ----
ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point()
"#;
        let metadata = BundleMetadata::new("test-bundle".to_string());
        let rmd = generator.from_document("analysis.R", doc_content, &metadata);

        assert!(rmd.contains("## Setup"));
        assert!(rmd.contains("## Analysis"));
        assert!(rmd.contains("library(ggplot2)"));
        assert!(rmd.contains("ggplot(mtcars"));
    }

    #[test]
    fn test_document_export_empty_content() {
        let options = RMarkdownOptions {
            mode: ExportMode::Document,
            ..Default::default()
        };
        let generator = RMarkdownGenerator::new(options);

        let doc_content = "";
        let metadata = BundleMetadata::new("test-bundle".to_string());
        let rmd = generator.from_document("empty.R", doc_content, &metadata);

        assert!(rmd.contains("---"));
        assert!(rmd.contains("title:"));
        assert!(rmd.contains("empty"));
    }

    #[test]
    fn test_format_timestamp() {
        let ms = 1699200000000u64; // 2023-11-05 14:40:00 UTC
        let formatted = format_timestamp(ms);

        assert!(formatted.contains("2023"));
        assert!(formatted.contains("UTC"));
    }

    #[test]
    fn test_export_mode_default() {
        let mode = ExportMode::default();
        assert_eq!(mode, ExportMode::Timeline);
    }

    #[test]
    fn test_rmarkdown_options_default() {
        let options = RMarkdownOptions::default();
        assert_eq!(options.mode, ExportMode::Timeline);
        assert!(options.include_timestamps);
        assert!(options.show_actor);
        assert!(options.embed_plots);
        assert!(options.include_outputs);
        assert!(!options.include_errors);
        assert!(options.include_summary);
    }
}
