use reprod_core::export::{
    BundleMetadata, CodeFolding, ExportMode, RMarkdownGenerator, RMarkdownOptions,
    ReproductionBundle,
};
use reprod_core::protocol::{
    CodeBlockKind, CodeBlockMetadata, EnvironmentSnapshot, ExecutionActor, ExecutionContext,
    ExecutionEvent, ExecutionResult, ExecutionSource, PlotInfo,
};

/// Create a realistic execution event for testing.
fn create_test_event(
    event_id: &str,
    document: &str,
    code: &str,
    actor: ExecutionActor,
    has_plot: bool,
    has_error: bool,
    timestamp: u64,
) -> ExecutionEvent {
    let plots = if has_plot {
        vec![PlotInfo {
            id: format!("{}-plot", event_id),
            filename: format!("{}_plot.png", event_id),
            // Small 1x1 red PNG
            base64_data: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg==".to_string(),
            index: 0,
            width: None,
            height: None,
            timestamp: Some(timestamp),
            code: Some(code.to_string()),
            storage_path: Some(format!(".reprod/plots/{}_plot.png", event_id)),
            snapshot_path: None,
        }]
    } else {
        vec![]
    };

    ExecutionEvent {
        event_id: event_id.to_string(),
        context: ExecutionContext {
            source: ExecutionSource::Cell,
            document_path: Some(document.to_string()),
            cell_index: Some(1),
            triggered_at_ms: timestamp,
            actor,
        },
        blocks: vec![CodeBlockMetadata {
            id: format!("{}-block", event_id),
            index: 0,
            kind: CodeBlockKind::Section,
            label: Some("Test Block".to_string()),
            start_line: 1,
            end_line: 3,
            code: code.to_string(),
        }],
        result: ExecutionResult {
            success: !has_error,
            output: if has_error {
                String::new()
            } else {
                "[1] Success".to_string()
            },
            error: if has_error {
                Some("Error: test error".to_string())
            } else {
                None
            },
            plots,
            execution_time_ms: 42,
        },
        environment: EnvironmentSnapshot {
            r_path: "Rscript".to_string(),
            working_dir: "/tmp/test-project".to_string(),
            temp_dir: "/tmp/reprod-test".to_string(),
        },
        created_at_ms: timestamp + 100,
    }
}

#[test]
fn test_rmarkdown_timeline_export_integration() {
    // Create a realistic timeline with mixed User/AI events
    let start_time = 1699200000000_u64;

    let events = vec![
        create_test_event(
            "evt-001",
            "analysis.R",
            "library(ggplot2)\nlibrary(dplyr)",
            ExecutionActor::User,
            false,
            false,
            start_time,
        ),
        create_test_event(
            "evt-002",
            "analysis.R",
            "data <- read.csv('input.csv')\nhead(data)",
            ExecutionActor::User,
            false,
            false,
            start_time + 1000,
        ),
        create_test_event(
            "evt-003",
            "analysis.R",
            "# AI suggested: Filter outliers\ndata_clean <- data %>% filter(value < 100)",
            ExecutionActor::Ai,
            false,
            false,
            start_time + 2000,
        ),
        create_test_event(
            "evt-004",
            "plots.R",
            "ggplot(data_clean, aes(x, y)) + geom_point()",
            ExecutionActor::User,
            true,
            false,
            start_time + 3000,
        ),
        create_test_event(
            "evt-005",
            "plots.R",
            "# AI suggested: Add regression line\nggplot(data_clean, aes(x, y)) + geom_point() + geom_smooth()",
            ExecutionActor::Ai,
            true,
            false,
            start_time + 4000,
        ),
    ];

    let bundle = ReproductionBundle::from_events(events);

    // Generate RMarkdown with all options enabled
    let options = RMarkdownOptions {
        mode: ExportMode::Timeline,
        show_code: true,
        code_folding: CodeFolding::Show,
        include_timestamps: true,
        show_actor: true,
        embed_plots: true,
        include_outputs: true,
        include_errors: true,
        include_summary: true,
        output_head_lines: 20,
        output_tail_lines: 8,
        output_max_lines: 200,
    };

    let generator = RMarkdownGenerator::new(options);
    let rmd_content = generator.from_timeline(&bundle);

    // Verify YAML header
    assert!(rmd_content.contains("---"));
    assert!(rmd_content.contains("title: \"Re-prod Analysis Report (Timeline Export)\""));
    assert!(rmd_content.contains("author: \"Generated by Re-prod\""));
    assert!(rmd_content.contains("output:"));
    assert!(rmd_content.contains("html_document:"));
    // Verify new style configurations
    assert!(rmd_content.contains("geometry: \"margin=1in\""));
    assert!(rmd_content.contains("fontsize: 11pt"));
    assert!(rmd_content.contains("\\usepackage{helvet}"));
    assert!(rmd_content.contains("\\renewcommand{\\familydefault}{\\sfdefault}"));

    // Verify session info
    assert!(rmd_content.contains("# Session Information"));
    assert!(rmd_content.contains("Bundle ID"));
    assert!(rmd_content.contains("Total Events"));
    assert!(rmd_content.contains("Duration"));

    // Verify timeline export section
    assert!(rmd_content.contains("# Timeline Export"));
    assert!(rmd_content.contains("actual execution history"));

    // Verify events are present
    assert!(rmd_content.contains("## Event 1 - User"));
    assert!(rmd_content.contains("## Event 2 - User"));
    assert!(rmd_content.contains("## Event 3 - AI Assistant"));
    assert!(rmd_content.contains("## Event 4 - User"));
    assert!(rmd_content.contains("## Event 5 - AI Assistant"));

    // Verify code chunks
    assert!(rmd_content.contains("```{r event-1-block-0}"));
    assert!(rmd_content.contains("library(ggplot2)"));
    assert!(rmd_content.contains("library(dplyr)"));
    assert!(rmd_content.contains("data <- read.csv('input.csv')"));
    assert!(rmd_content.contains("# AI suggested: Filter outliers"));
    assert!(rmd_content.contains("ggplot(data_clean, aes(x, y)) + geom_point()"));

    // Verify outputs
    assert!(rmd_content.contains("::: {.rp-output}"));
    assert!(rmd_content.contains("[1] Success"));

    // Verify plots
    assert!(rmd_content.contains("![Plot](evt-004_plot.png)"));
    assert!(rmd_content.contains("![Plot](evt-005_plot.png)"));

    // Verify session summary
    assert!(rmd_content.contains("# Session Summary"));
    assert!(rmd_content.contains("## Statistics"));
    assert!(rmd_content.contains("Total Executions"));
    assert!(rmd_content.contains("User Actions"));
    assert!(rmd_content.contains("AI Actions"));
    assert!(rmd_content.contains("Total Plots"));
    assert!(rmd_content.contains("## Environment"));

    // Verify footer
    assert!(rmd_content.contains("*Generated by Re-prod - Reproducible R Analysis Environment*"));

    println!("✓ RMarkdown timeline export integration test passed!");
    println!(
        "  - Generated {} bytes of RMarkdown content",
        rmd_content.len()
    );
    println!("  - Verified YAML header structure");
    println!("  - Verified all 5 events with correct actors");
    println!("  - Verified code chunks and outputs");
    println!("  - Verified plot embeddings");
    println!("  - Verified session summary");
}

#[test]
fn test_rmarkdown_document_export_integration() {
    // Create a sample R document
    let doc_content = r#"# Setup ----
library(ggplot2)
library(dplyr)

# Load Data ----
data <- read.csv("input.csv")
data_clean <- data %>% filter(!is.na(value))

# Analysis ----
summary(data_clean)
model <- lm(y ~ x, data = data_clean)

# Visualization ----
ggplot(data_clean, aes(x = x, y = y)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_minimal()
"#;

    let metadata = BundleMetadata::new("test-document-export".to_string());

    let options = RMarkdownOptions {
        mode: ExportMode::Document,
        code_folding: CodeFolding::Show,
        show_code: true,
        include_timestamps: false,
        show_actor: false,
        embed_plots: false,
        include_outputs: false,
        include_errors: false,
        include_summary: false,
        output_head_lines: 20,
        output_tail_lines: 8,
        output_max_lines: 200,
    };

    let generator = RMarkdownGenerator::new(options);
    let rmd_content = generator.from_document("analysis.R", doc_content, &metadata);

    // Verify YAML header
    assert!(rmd_content.contains("---"));
    assert!(rmd_content.contains("title: \"analysis\""));
    assert!(rmd_content.contains("author: \"Generated by Re-prod\""));

    // Verify new style configurations
    assert!(rmd_content.contains("geometry: \"margin=1in\""));
    assert!(rmd_content.contains("fontsize: 11pt"));
    assert!(rmd_content.contains("\\usepackage{helvet}"));
    assert!(rmd_content.contains("\\renewcommand{\\familydefault}{\\sfdefault}"));

    // Verify document overview
    assert!(rmd_content.contains("# Overview"));
    assert!(rmd_content.contains("analysis.R"));

    // Verify sections
    assert!(rmd_content.contains("## Setup"));
    assert!(rmd_content.contains("## Load Data"));
    assert!(rmd_content.contains("## Analysis"));
    assert!(rmd_content.contains("## Visualization"));

    // Verify code content
    assert!(rmd_content.contains("library(ggplot2)"));
    assert!(rmd_content.contains("library(dplyr)"));
    assert!(rmd_content.contains("read.csv(\"input.csv\")"));
    assert!(rmd_content.contains("ggplot(data_clean"));
    assert!(rmd_content.contains("geom_point()"));
    assert!(rmd_content.contains("geom_smooth(method = \"lm\")"));

    // Verify R code chunks
    assert!(rmd_content.contains("```{r chunk-"));

    // Verify footer
    assert!(rmd_content.contains("*Generated by Re-prod*"));
    // The bundle ID is in the metadata but not necessarily in the visible content
    // Just verify the export metadata section exists
    assert!(rmd_content.contains("*Exported:"));

    // Should NOT contain timeline-specific elements
    assert!(!rmd_content.contains("Event 1"));
    assert!(!rmd_content.contains("User"));
    assert!(!rmd_content.contains("AI Assistant"));
    assert!(!rmd_content.contains("actual execution history"));

    println!("✓ RMarkdown document export integration test passed!");
    println!(
        "  - Generated {} bytes of RMarkdown content",
        rmd_content.len()
    );
    println!("  - Verified YAML header structure");
    println!("  - Verified section headers extracted from R comments");
    println!("  - Verified code content preservation");
    println!("  - Verified no timeline-specific elements");
}

#[test]
fn test_rmarkdown_export_with_errors() {
    let start_time = 1699200000000_u64;

    let events = vec![
        create_test_event(
            "evt-001",
            "test.R",
            "x <- 1:10",
            ExecutionActor::User,
            false,
            false,
            start_time,
        ),
        create_test_event(
            "evt-002",
            "test.R",
            "y <- x / 0  # This will create Inf",
            ExecutionActor::User,
            false,
            true,
            start_time + 1000,
        ),
        create_test_event(
            "evt-003",
            "test.R",
            "z <- log(-1)  # This will create NaN",
            ExecutionActor::User,
            false,
            true,
            start_time + 2000,
        ),
    ];

    let bundle = ReproductionBundle::from_events(events);

    // Test with errors included
    let options_with_errors = RMarkdownOptions {
        mode: ExportMode::Timeline,
        code_folding: CodeFolding::Show,
        show_code: true,
        include_timestamps: false,
        show_actor: false,
        embed_plots: false,
        include_outputs: false,
        include_errors: true,
        include_summary: false,
        output_head_lines: 20,
        output_tail_lines: 8,
        output_max_lines: 200,
    };

    let generator = RMarkdownGenerator::new(options_with_errors.clone());
    let rmd_with_errors = generator.from_timeline(&bundle);

    assert!(rmd_with_errors.contains("::: {.rp-error}"));
    assert!(rmd_with_errors.contains("Error: test error"));

    // Test with errors excluded
    let options_without_errors = RMarkdownOptions {
        include_errors: false,
        ..options_with_errors
    };

    let generator = RMarkdownGenerator::new(options_without_errors);
    let rmd_without_errors = generator.from_timeline(&bundle);

    assert!(!rmd_without_errors.contains("::: {.rp-error}"));

    println!("✓ RMarkdown error handling integration test passed!");
}

#[test]
fn test_rmarkdown_export_options_combinations() {
    let start_time = 1699200000000_u64;

    let events = vec![
        create_test_event(
            "evt-001",
            "test.R",
            "x <- rnorm(100)",
            ExecutionActor::User,
            false,
            false,
            start_time,
        ),
        create_test_event(
            "evt-002",
            "test.R",
            "plot(x)",
            ExecutionActor::Ai,
            true,
            false,
            start_time + 1000,
        ),
    ];

    let bundle = ReproductionBundle::from_events(events);

    // Test 1: Minimal options
    let minimal_options = RMarkdownOptions {
        mode: ExportMode::Timeline,
        code_folding: CodeFolding::Show,
        show_code: true,
        include_timestamps: false,
        show_actor: false,
        embed_plots: false,
        include_outputs: false,
        include_errors: false,
        include_summary: false,
        output_head_lines: 20,
        output_tail_lines: 8,
        output_max_lines: 200,
    };

    let generator = RMarkdownGenerator::new(minimal_options);
    let minimal_rmd = generator.from_timeline(&bundle);

    assert!(minimal_rmd.contains("```{r"));
    assert!(minimal_rmd.contains("x <- rnorm(100)"));
    assert!(!minimal_rmd.contains("User"));
    assert!(!minimal_rmd.contains("AI Assistant"));
    assert!(!minimal_rmd.contains("::: {.rp-output}"));
    assert!(!minimal_rmd.contains("![Plot]"));
    assert!(!minimal_rmd.contains("# Session Summary"));

    // Test 2: Full options
    let full_options = RMarkdownOptions {
        mode: ExportMode::Timeline,
        code_folding: CodeFolding::Show,
        show_code: true,
        include_timestamps: true,
        show_actor: true,
        embed_plots: true,
        include_outputs: true,
        include_errors: true,
        include_summary: true,
        output_head_lines: 20,
        output_tail_lines: 8,
        output_max_lines: 200,
    };

    let generator = RMarkdownGenerator::new(full_options);
    let full_rmd = generator.from_timeline(&bundle);

    assert!(full_rmd.contains("Event 1 - User"));
    assert!(full_rmd.contains("Event 2 - AI Assistant"));
    assert!(full_rmd.contains("**Executed**:"));
    assert!(full_rmd.contains("::: {.rp-output}"));
    assert!(full_rmd.contains("![Plot](evt-002_plot.png)"));
    assert!(full_rmd.contains("# Session Summary"));

    println!("✓ RMarkdown options combinations test passed!");
    println!("  - Tested minimal options configuration");
    println!("  - Tested full options configuration");
    println!("  - Verified option flags control output correctly");
}
